/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BpPersistentStorage {
        "dbname": string;
        "dbstorename": string;
        "dbversion": number;
        "getKey": (key: string) => Promise<object>;
        "setKey": (key: string, value: object) => Promise<object>;
    }
}
declare global {
    interface HTMLBpPersistentStorageElement extends Components.BpPersistentStorage, HTMLStencilElement {
    }
    var HTMLBpPersistentStorageElement: {
        prototype: HTMLBpPersistentStorageElement;
        new (): HTMLBpPersistentStorageElement;
    };
    interface HTMLElementTagNameMap {
        "bp-persistent-storage": HTMLBpPersistentStorageElement;
    }
}
declare namespace LocalJSX {
    interface BpPersistentStorage {
        "dbname"?: string;
        "dbstorename"?: string;
        "dbversion"?: number;
    }
    interface IntrinsicElements {
        "bp-persistent-storage": BpPersistentStorage;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bp-persistent-storage": LocalJSX.BpPersistentStorage & JSXBase.HTMLAttributes<HTMLBpPersistentStorageElement>;
        }
    }
}
